DROP TABLE IF EXISTS expert;

CREATE TABLE expert (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS market;

CREATE TABLE market (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS product;

CREATE TABLE product (
                       id INT AUTO_INCREMENT  PRIMARY KEY,
                       name VARCHAR(255) NOT NULL
);
