DROP TABLE IF EXISTS expert;

CREATE TABLE expert (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS expert;

CREATE TABLE expert (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);
